
services:
  api: &api
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    image: minders_haven_prod_api
    container_name: minders_haven_prod_api
    volumes:
      - .:/app:z
      - ./staticfiles:/app/staticfiles
    #ports:
    #  - "8000:8000"
    expose:
      - "8000"
    env_file:
      - ./.envs/.env.local
    depends_on:
      - postgres
      - mailpit
      - redis
    command: /start
    networks:
      - minders_haven_prod_nw

  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    image: minders_haven_prod_postgres
    container_name: minders_haven_prod_postgres
    ports:
      - "5433:5433"
    volumes:
      - minders_haven_prod_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.env.local
    networks:
      - minders_haven_prod_nw

  mailpit:
    image: docker.io/axllent/mailpit:v1.15
    container_name: minders_haven_prod_mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:  
      - minders_haven_prod_mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1  
    networks:
      - minders_haven_prod_nw

  client:
    build:
      context: ./client
      dockerfile: ./docker/local/Dockerfile
    container_name: minders_haven_client
    image: minders_haven_client
    #ports:
    #  - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - minders_haven_prod_nw

  redis:
    image: redis:7.0-alpine3.19
    command: redis-server --appendonly yes
    container_name: minders_haven_redis
    volumes:
      - minders_haven_redis_prod_data:/data
    networks:
      - minders_haven_prod_nw

  celeryworker:
    <<: *api
    image: minders_haven_prod_celeryworker
    container_name: minders_haven_prod_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *api
    image: minders_haven_prod_celerybeat
    container_name: minders_haven_prod_celerybeat
    command: /start-celerybeat
   
  flower:
    <<: *api
    image: minders_haven_prod_flower
    container_name: minders_haven_prod_flower
    ports:
      - "5555:5555"
    command: /start-flower

  
  nginx:
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    restart: always
    container_name: minders_haven_nginx
    ports:
      - "8080:80"
    volumes:
      - ./staticfiles:/app/staticfiles
      - logs_store:/var/log/nginx
    depends_on:
      - api
    networks:
      - minders_haven_prod_nw
    

networks:
  minders_haven_prod_nw:
    external: true

volumes:
  minders_haven_prod_postgres_data: {}
  minders_haven_prod_mailpit_data: {}
  logs_store: {}
  minders_haven_redis_prod_data: {}

