# Generated by Django 4.2.11 on 2024-07-29 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slot_date", models.DateField()),
                ("slot_time", models.TimeField()),
                ("duration", models.IntegerField()),
                ("number_of_kids", models.IntegerField()),
                ("kids_age", models.CharField(max_length=20)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("parent_location", "Parent Location"),
                            ("minder_location", "Minder Location"),
                        ],
                        default="minder_location",
                        max_length=30,
                        verbose_name="Location",
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(verbose_name="Additional Information"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("completed", "Completed"),
                            ("in_review", "In Review"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "completed_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="Completed On"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_to_slots",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned to",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by_slots",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
