# Generated by Django 4.2.11 on 2024-07-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="slot",
            name="in_review_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="slot",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="slot",
            name="additional_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="Additional Information"
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("in_review", "In Review"),
                    ("completed", "Completed"),
                ],
                default="submitted",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
