# Generated by Django 4.2.11 on 2024-08-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slots", "0003_remove_slot_in_review_date_remove_slot_is_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="slot",
            name="payment_intent_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Payment Intent ID"
            ),
        ),
        migrations.AddField(
            model_name="slot",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Payment Status",
            ),
        ),
    ]
