# Generated by Django 4.2.11 on 2024-08-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slots", "0005_remove_slot_payment_intent_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="slot",
            name="total_price",
            field=models.FloatField(default="0.00"),
        ),
    ]
