# Generated by Django 4.2.11 on 2024-08-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("slots", "0006_slot_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slot",
            name="total_price",
        ),
    ]
