# Generated by Django 4.2.11 on 2024-08-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slots", "0008_slot_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=8, verbose_name="Total Price"
            ),
        ),
    ]
