# Generated by Django 4.2.11 on 2024-08-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_display_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="display_image",
        ),
    ]
